### ISSUE TITLE
One-Click Account Setup not working

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum-webapp#57]
The one-click account setup on https://prototype.pendulumchain.org is not working. When clicking on the button, there is a long list of commands that get executed but after that nothing seems to change and the webapp still shows the message "Connect your account".

Maybe it is related to the Stellar testnet reset, but I executed the reset script yesterday and that should not be an issue anymore.

**Comment by gonzamontiel** [comment]
hey, I believe this is related with the fact that our collator node stopped working: https://github.com/pendulum-chain/pendulum/issues/21

**Comment by gonzamontiel** [comment]
Indeed, I tested it against a standalone chain, and it works just fine. I will leave this issue open though, and we cna close it when the related ticket is merged.

**Comment by gonzamontiel** [comment]
Collator node is running again. Closing after https://github.com/pendulum-chain/pendulum/issues/21 is closed
