### ISSUE TITLE
Add small utility modal to convert between address formats

### ISSUE THREAD

**Issue by gonzamontiel** [pendulum-chain/pendulum-webapp#59]
For different testing purposes, we could use a tool for converting between different address formats, like stellar encoding, SS58, hexa, etc. 
Add a button in the topbar, that shows a simple modal with an input for converting among different address formats.
Design TBD.

**Comment by TorstenStueber** [comment]
Please note that the conversion of binary Stellar keys to string encoded Stellar keys should never be required in the future. The extrinsic should just accept a string, which is the Stellar encoding. But this is good for now.
