### ISSUE TITLE
Typings for props

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum-webapp#62]
Props of all components should be typed and not `any` (see e.g., the current state of [`AccountDialog`](https://github.com/pendulum-chain/pendulum-webapp/blob/main/src/components/AccountDialog.tsx)).

**Comment by erasmus** [comment]
@TorstenStueber seems done. Can we close?

**Comment by TorstenStueber** [comment]
Looks done. Closed.
