### ISSUE TITLE
SBP: One-click not working

### ISSUE THREAD

**Issue by NachoPal** [pendulum-chain/pendulum-webapp#71]
The One-click setup does not provide a private key. It just returns: “Adding trustlines for EUR and USDC Stellar assets.”

**Comment by ebma** [comment]
Hey @NachoPal, the one-click setup failed because the account issuing the EUR and USDC assets on Stellar was not initialized/funded again after a recent testnet reset. I initialized it again and the one-click setup should work now. Sorry for the inconvenience.
